name: Deploy Vue Frontend to Flask

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies & build
        run: |
          npm install
          npm run build

      - name: Setup SSH access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy built frontend to Flask server
        run: |
          # Copy index.html to Flask templates/
          scp dist/index.html ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/aditya/first-deployment/templates/

          # Copy assets to Flask static/
          scp -r dist/assets ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/aditya/first-deployment/static/

      - name: Restart Flask app via Supervisor
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            sudo supervisorctl restart portfolio
          EOF
